import { GameNav } from "@/components/GameNav";
import { formatDateTime, formatPoints } from "@/lib/game";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardList, Loader2, XCircle } from "lucide-react";

export default function History() {
  const { data, isLoading } = trpc.game.history.useQuery();
  if (isLoading) return <div className="auth-screen"><Loader2 className="animate-spin text-teal-200" /></div>;
  const totals = data?.totals ?? { answered: 0, correct: 0, points: 0 };
  return <div className="app-bg"><GameNav /><main className="page-shell"><p className="eyebrow">Painel de desempenho</p><h1 className="page-title">A sua trajetória <span className="text-teal-200">na disputa.</span></h1><p className="page-intro">Acompanhe respostas, acertos e pontos consolidados depois das rodadas.</p>
    <section className="score-grid"><article className="glass-card metric-card"><p className="metric-label">Pontos confirmados</p><p className="metric-value">{formatPoints(totals.points)}</p><p className="metric-sub">resultado processado</p></article><article className="glass-card metric-card"><p className="metric-label">Taxa de acerto</p><p className="metric-value">{data?.accuracy ?? 0}%</p><p className="metric-sub">{totals.correct} acertos em {totals.answered}</p></article><article className="glass-card metric-card"><p className="metric-label">Rodadas concluídas</p><p className="metric-value">{data?.history.length ?? 0}</p><p className="metric-sub">com pontuação disponível</p></article></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-[1fr_.7fr]"><article className="glass-card p-6"><div className="flex items-center gap-2"><ClipboardList className="text-teal-200" size={19} /><h2 className="font-display text-xl font-bold">Resultados por rodada</h2></div><div className="mt-5">{data?.history.map(item => <div className="team-row py-4" key={item.roundId}><span className="team-avatar h-9 w-9 text-sm bg-teal-300/15 text-teal-100"><CheckCircle2 size={17} /></span><div><p className="team-name">{item.title}</p><p className="mt-1 text-[11px] text-slate-400">{formatDateTime(item.startsAt)} · {item.correctCount} acertos / {item.answeredCount} respostas</p></div><span className="team-points text-base">+{formatPoints(item.points)}</span></div>)}{!data?.history.length && <div className="empty-panel">Seus resultados vão aparecer aqui quando a primeira rodada for processada.</div>}</div></article>
      <article className="glass-card p-6"><h2 className="font-display text-xl font-bold">Ajustes administrativos</h2><p className="mt-2 text-xs leading-5 text-slate-400">Apenas ajustes realizados pela administração ficam registrados nesta área.</p><div className="mt-5">{data?.adjustments.map(item => <div className="team-row" key={item.id}><span className="team-avatar h-8 w-8 bg-orange-300/10 text-orange-200"><XCircle size={16} /></span><p className="team-name">{item.reason}</p><span className={item.points > 0 ? "team-points text-teal-100" : "team-points text-orange-200"}>{item.points > 0 ? "+" : ""}{formatPoints(item.points)}</span></div>)}{!data?.adjustments.length && <div className="empty-panel">Nenhum ajuste registrado.</div>}</div></article></section>
  </main></div>;
}
