import { GameNav } from "@/components/GameNav";
import { formatPoints } from "@/lib/game";
import { trpc } from "@/lib/trpc";
import { Activity, Loader2, UsersRound } from "lucide-react";

export default function Team() {
  const { data, isLoading } = trpc.game.myTeam.useQuery(undefined, { refetchInterval: 10_000, refetchOnMount: "always" });
  if (isLoading) return <div className="auth-screen"><Loader2 className="animate-spin text-teal-200" /></div>;
  if (!data?.team) return <div className="app-bg"><GameNav /><main className="page-shell"><div className="glass-card empty-panel">Conclua o cadastro para visualizar sua equipe.</div></main></div>;
  const { team, history } = data; const top = Math.max(...history.map(item => item.points), 1);
  return <div className="app-bg"><GameNav /><main className="page-shell"><p className="eyebrow">Sua aliança na arena</p><div className="mt-3 flex flex-wrap items-center gap-4"><span className="team-avatar h-16 w-16 text-3xl" style={{ background: `linear-gradient(135deg, ${team.color}, ${team.accentColor})` }}>{team.symbol}</span><div><h1 className="page-title m-0">Equipe {team.name}</h1><p className="mt-1 text-sm text-slate-300">{team.description}</p></div></div>
    <section className="score-grid"><article className="glass-card metric-card"><p className="metric-label">Pontuação total</p><p className="metric-value">{formatPoints(team.points)}</p><p className="metric-sub">pontos acumulados</p></article><article className="glass-card metric-card"><p className="metric-label">Posição geral</p><p className="metric-value">#{team.rank}</p><p className="metric-sub">no ranking de equipes</p></article><article className="glass-card metric-card"><p className="metric-label">Média da equipe</p><p className="metric-value">{formatPoints(team.averagePoints)}</p><p className="metric-sub">por participante</p></article></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="glass-card p-6"><div className="flex items-center gap-2"><Activity className="text-teal-200" size={19} /><h2 className="font-display text-lg font-bold">Evolução da pontuação</h2></div><div className="mt-7 flex h-52 items-end gap-3">{history.length ? history.map(item => <div className="flex h-full flex-1 flex-col items-center justify-end gap-2" key={item.roundId}><span className="text-[10px] font-mono text-teal-100">{item.points}</span><div className="w-full max-w-10 rounded-t-md" style={{ height: `${Math.max(9, (item.points / top) * 100)}%`, background: `linear-gradient(180deg, ${team.accentColor}, ${team.color})` }} /><span className="max-w-14 truncate text-[10px] text-slate-400">{item.title}</span></div>) : <div className="empty-panel w-full">A evolução aparecerá ao fim da primeira rodada.</div>}</div></article>
      <article className="glass-card p-6"><div className="flex items-center gap-2"><UsersRound className="text-orange-200" size={19} /><h2 className="font-display text-lg font-bold">Integrantes</h2></div><div className="mt-4">{team.members.map(member => <div className="team-row" key={member.participantId}><span className="team-avatar h-8 w-8 text-xs" style={{ background: team.color }}>{member.nickname.slice(0, 1).toUpperCase()}</span><p className="team-name">{member.nickname}</p><span className="team-points">{formatPoints(member.points)}</span></div>)}{!team.members.length && <div className="empty-panel">A equipe ainda não tem integrantes.</div>}</div></article></section>
  </main></div>;
}
